### ISSUE TITLE
Radio Button Selection issue

### ISSUE THREAD

**Issue by zswalker** [CSC-256-Group-Project-9/group-9-webapp#5]
Issue Description: 'for' attribute values are labeled incorrectly.
Elaboration: This issue is causing incorrect selection when clicking the label associated with the radio button.

Code snippet of issue:
![image](https://github.com/CSC-256-Group-Project-9/group-9-webapp/assets/103614234/5edf24e3-b7e3-4311-b822-7c501b4a2536)

**Comment by HaffCaff** [comment]
@zswalker Pushed changed, `git pull` and let me know if it works!

**Comment by zswalker** [comment]
@HaffCaff Almost, the Java option is still not working as expected. ('id' attribute is lowercase, 'for' attribute is capital)

**Comment by HaffCaff** [comment]
Ahh, good catch, eyes were going cross-eyed at that point. Pushed fix [here](https://github.com/CSC-256-Group-Project-9/group-9-webapp/pull/6) added you as reviewer
