### ISSUE TITLE
Tests Cut Off For Users With Short Screens!

### ISSUE THREAD

**Issue by yeah5000** [CSC-256-Group-Project-9/group-9-webapp#7]
**The issue:**

The tests get cut off when the window containing the web app gets shortened. This may be an issue for individuals with smaller screens and is an issue due to the formatting of the HTML.

**Steps to replicate:**

Open the web app, use the right side of the window to drag in order to make the browser window thinner.
**OR**
have a thin screen and open the web app as usual.

**Image of the issue:**
![image](https://github.com/CSC-256-Group-Project-9/group-9-webapp/assets/103586054/8e56d28d-2b13-421a-bf31-8bc52b91e885)

**Comment by HaffCaff** [comment]
Fixed CSS, created another test container to display inline



![Image](https://github.com/CSC-256-Group-Project-9/group-9-webapp/assets/31331413/89f88ecf-0f16-4ed8-9ab2-b8fa0287afd9)

**Comment by yeah5000** [comment]
Issue has been resolved and verified!
